-- AlterTable
ALTER TABLE `order` ADD COLUMN `amount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `currency` VARCHAR(191) NOT NULL DEFAULT 'THB',
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `stripePaymentId` VARCHAR(191) NOT NULL DEFAULT '';
